### ISSUE TITLE
faraday-proxy Does Not Fail Gracefully if Unconfigured

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Software#208]
## Summary
After installing faraday-proxy you must configure the `proxy.ini` file with a `faraday-proxy --init-config` and then run `faraday-proxy --callsign xxx --nodeid x --port xxx`. If one just installs faraday and then attempts to run `faraday-proxy` there is an hard failure and the program quits. This should nicely tell the user what is wrong and how to fix it.

## Problem Explanation
Error message:

```
Bryce@BRYCE-SP4 MINGW64 ~/Documents/GitHub/faradayrf-kb1lqc (issue191)
$ faraday-proxy
Traceback (most recent call last):
  File "C:\Users\Bryce\Documents\GitHub\faradayrf-kb1lqc\test\Scripts\faraday-proxy-script.py", line 11, in <module>
    load_entry_point('faraday', 'console_scripts', 'faraday-proxy')()
  File "c:\users\bryce\documents\github\faradayrf-kb1lqc\test\lib\site-packages\pkg_resources\__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\bryce\documents\github\faradayrf-kb1lqc\test\lib\site-packages\pkg_resources\__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "c:\users\bryce\documents\github\faradayrf-kb1lqc\test\lib\site-packages\pkg_resources\__init__.py", line 2303, in load
    return self.resolve()
  File "c:\users\bryce\documents\github\faradayrf-kb1lqc\test\lib\site-packages\pkg_resources\__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\bryce\documents\github\faradayrf-kb1lqc\faraday\proxy.py", line 216, in <module>
    configureProxy(args, proxyConfigPath)
  File "c:\users\bryce\documents\github\faradayrf-kb1lqc\faraday\proxy.py", line 173, in configureProxy
    config.set(unit, 'BAUDRATE', args.baudrate)
  File "C:\python27\Lib\ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'UNIT0'
```

#### Software 
Faraday software

#### Hardware
All

# Supporting Information
N/A

**Comment by kb1lqd** [comment]
#235 closes this.
